-- nixarchy.microvm: open the MicroVMs menu from the keyboard.
--
-- Lives in ~/.config/hypr/microvm-binds.lua. With Nix, the flake's Home
-- Manager module writes it (programs.nixarchy-microvm.keybinding). Without
-- Nix, copy this file there from the plugin folder. Either way,
-- ~/.config/hypr/bindings.lua loads it with
--
--   pcall(require, "hypr.microvm-binds")
--
-- pcall, not a bare require: bindings.lua is yours and outlives this file,
-- and a missing module in a bare require takes the whole config down.
--
-- The description is what Omarchy's key bindings menu (Super+K) lists.
o.bind("SUPER + ALT + V", "MicroVMs", "omarchy-shell shell toggle nixarchy.microvm '{}'")
